# Generated by Django 3.0.4 on 2020-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListAllDefects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuename', models.CharField(max_length=300)),
                ('originator', models.CharField(max_length=20)),
                ('addinfo', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=20)),
                ('createddate', models.CharField(max_length=30)),
                ('expecteddate', models.DateField()),
            ],
        ),
     
    ]
