# Generated by Django 3.0.4 on 2020-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAllDefects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuename', models.CharField(max_length=300)),
                ('originator', models.CharField(max_length=20)),
                ('addinfo', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=20)),
                ('createddate', models.CharField(max_length=30)),
                ('expecteddate', models.DateField()),
                
            ],
        ),
    ]
