# Generated by Django 3.0.4 on 2020-04-07 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_listalldefects1'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='listalldefects1',
        #     name='oremailid',
        # ),
        # migrations.RemoveField(
        #     model_name='listalldefects1',
        #     name='status',
        # ),
        # migrations.AddField(
        #     model_name='listalldefects',
        #     name='oremailid',
        #     field=models.EmailField(default=django.utils.timezone.now, max_length=254),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='listalldefects',
            name='sample',
            field=models.CharField(default="No Mail", max_length=20),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='listalldefects',
        #     name='status',
        #     field=models.CharField(default='no status', max_length=20),
        #     preserve_default=False,
        # ),
    ]
